# Generated by Django 4.1.5 on 2023-01-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_alter_worker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='work_app.category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='work_app.worker'),
        ),
    ]
