# Generated by Django 4.1.5 on 2023-01-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0004_alter_work_category_alter_work_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_app.category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_app.worker'),
        ),
    ]
