# Generated by Django 4.1.5 on 2023-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0005_alter_work_category_alter_work_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
