# Generated by Django 4.1.5 on 2023-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0006_worker_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
